[workspace]
resolver = "2"
members = ["backend"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
debug = false

[profile.release.package."*"]
opt-level = "s"
codegen-units = 1
debug = "limited"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
debug = "limited"
